version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Initialize the repository as a library
          command: npm run init
      - run:
          name: Install dependencies again! (REMOVE IF NOT REQUIRED)
          command: npm install
      - run:
          name: Lint all source
          command: npm start prerequisites.lint
      - run:
          name: Run all unit tests
          command: npm test
      - run:
          name: Remove dist folder if one exists
          command: npm start prerequisites.build
      - run:
          name: Transpile and package up the library
          command: npm start build
      - run:
          name: Generate Coverage to verify generation works
          command: npm start coverage.generate
      - run:
          name: Generate Documentation pages to verify generation works
          command: |
            npm start documentation.generate
